# SPDX-License-Identifier: GPL-2.0-only
subdir-ccflags-y += -I$(srctree)/arch/arm64/kvm/hyp/include/
subdir-ccflags-y += -DMODULE
hyp-obj-y := arm-smmu-v2.o tegra234-mc.o ../../../io-pgtable-arm.o
include $(srctree)/arch/arm64/kvm/hyp/nvhe/Makefile.module
